sync with fedora

diff --git a/setregdomain b/setregdomain
--- a/setregdomain
+++ b/setregdomain
@@ -18,52 +18,52 @@
 REGDOMAIN=/etc/sysconfig/regdomain
 LOCALTIME=/etc/localtime
 
-LOGGER="/usr/bin/logger -t crda"
+LOGGER="/bin/logger -t crda"
 
 getcountry() {
-	while read c a z r
-	do
-		if [ "$z" = "$ZONE" ]
-		then
-			echo $c
-			break
-		fi
-	done < /usr/share/zoneinfo/zone.tab
+    while read c a z r
+    do
+	if [ "$z" = "$ZONE" ]
+	then
+	    echo $c
+	    break
+	fi
+    done < /usr/share/zoneinfo/zone.tab
 }
 
 if [ -f $REGDOMAIN ]
 then
-	# This should set COUNTRY
-	. $REGDOMAIN
-	if [ -n "$COUNTRY" ]
-	then
-		iw reg set $COUNTRY
-		exit
-	fi
+    # This should set COUNTRY
+    . $REGDOMAIN
+    if [ -n "$COUNTRY" ]
+    then
+	/sbin/iw reg set $COUNTRY
+	exit
+    fi
 fi
 
 if [ -f "$LOCALTIME" ]
 then
-	ZONE=$(readlink -f $LOCALTIME)
-	ZONE=${ZONE#/usr/share/zoneinfo/}
+    ZONE=$(readlink -f $LOCALTIME)
+    ZONE=${ZONE#/usr/share/zoneinfo/}
 else
-	$LOGGER -s "Timezone information not found!  Unable to set regulatory domain."
-	exit 1
+    $LOGGER -s "Timezone information not found!  Unable to set regulatory domain."
+    exit 1
 fi
 
 if [ -z "$ZONE" -o "$ZONE" = "$LOCALTIME" ]
 then
-	$LOGGER -s "Could not determine timezone!  Unable to set regulatory domain."
-	exit 1
+    $LOGGER -s "Could not determine timezone!  Unable to set regulatory domain."
+    exit 1
 fi
 
 COUNTRY=$(getcountry)
 
 if [ -z "$COUNTRY" ]
 then
-	$LOGGER -s "Could not determine country!  Unable to set regulatory domain."
-	exit 1
+    $LOGGER -s "Could not determine country!  Unable to set regulatory domain."
+    exit 1
 fi
 
 $LOGGER "setting regulatory domain to $COUNTRY based on timezone ($ZONE)"
-iw reg set $COUNTRY
+/sbin/iw reg set $COUNTRY
